### ISSUE TITLE
Referring to integrated services as "devices" is semantically confusing

### ISSUE THREAD

**Issue by crawfordcomeaux** [connectordb/connectordb#309]
My understanding is that if I want to integrate RescueTime with CDB, I'd set it up as a "device" with the "writer" role. And I think the integration would need to have CDB pulling the data from RescueTime, as opposed to RescueTime pushing the data to CDB.

There are two confusing bits here: 
RescueTime is a service, not a device. 
CDB is reading/importing/streaming from RescueTime; RescueTime is not writing anything.

Ideas (from a CDB noob):
- Rework device/role concept into "inputs" & "outputs"
- I think it's more natural to me to think about integrations like this in terms of pub/sub instead of read/write, especially in the context of streams

**Comment by dkumor** [comment]
To ConnectorDB, RescueTime would be a device - it wouldn't need a writer role, since all devices can write to their own streams by default.

An integration with RescueTime would be achieved through the python API, which would somehow obtain the data from RescueTime, and input it to the database. This python program is referred to as the "device".

ConnectorDB can ship with several built-in integrations, but these integrations would work independently from the core data-gathering platform - each integration would be in effect its own service, and independent of the core CDB code. I would even suggest that these integrations be their own executables in an "integrations" or "plugins" subdirectory.

**Comment by crawfordcomeaux** [comment]
"Service" definitely makes more sense to me here. I'm used to seeing "integrations" in turnkey processes where I'll, at most, have to c/p some API keys.

**Comment by Grusinator** [comment]
I just recently stumbled upon this project, and find it quite interesting!

With regard to integrating with other services, would it make sense to make a new side project that handles the most used service integrations (such as rescueTime, withings, strava etc) using the python CDB API, maybe add some flask/django/web to handle oauth etc
maybe inspired by https://github.com/cpfair/tapiriik 

Are there something similar already implemented that i have not noticed yet?  

What is the intention with this project with respect to integrations?

**Comment by dkumor** [comment]
A separate syncing server is how it would work work ideally, for now: a service which integrates data from multiple places, and uses CDB as backend storage. There is currently no work on this.

Currently, my focus is on a machine-learning-based analysis server, which will run separately from CDB and attempt prediction, which is turning out to be a very difficult task. As such, I don't plan on writing an integration server myself until this is figured out, which might take a while.

If you are up to the task, it would be a wonderful addition!

**Comment by dkumor** [comment]
New version of CDB will have devices renamed to connections.
