### ISSUE TITLE
" illegal base64 data at input byte 8 " when adding a new device to the DB via Desktop Manager or Chrome plugin

### ISSUE THREAD

**Issue by proffalken** [connectordb/connectordb#319]
Hi,

I'm running the public alpha release of the system on my laptop, and I can access the web interface, sign up, log in and create manual entries into the system.

When I go to register a new device via either the Desktop Client or the Chrome Plugin, I can see a successful login in the application logs, however I get the following error:

```WARN[1228] illegal base64 data at input byte 8           addr=10.222.0.1:52558 code=403 dev=proffalken/user op=CreateDevice ref=36d20021-26ea-41ca-42d2-6e26a6f54c94 uri=/api/v1/crud/proffalken/gaiman-chrome
```

 I don't know if I'm missing an Admin account here, or whether I've just failed to setup my account properly, but I thought I'd ask here in case it's staring me straight in the face!

Full output from the logs when trying to sign up:

```
cxdb@fdc3a6498a75:/usr/share/connector_db/bin$ ./connectordb run /usr/share/connector_db/mydatabase/db/ --join
INFO[0000] Running ConnectorDB v0.3.0a1 at http://localhost:8000 (:8000) 
INFO[0026] User 'proffalken' Joined - 136.411023ms       addr=10.222.0.1:50102 op=JOIN uri=/join
INFO[0060] 0.07 queries/s                                active=0 authfails=0 errors=0 inserts=0 rest=4 web=1
WARN[0408] Can't access this resource.                   addr=10.222.0.1:50864 code=404 dev=proffalken/user op=ReadDevice ref=93f25ba4-72ae-40ae-557b-98a6eb6345b0 uri=/api/v1/crud/proffalken/laptop
INFO[0408] 1.169345ms                                    addr=10.222.0.1:50864 dev=proffalken/user op=ReadDevice uri=/api/v1/crud/proffalken/laptop
WARN[0408] illegal base64 data at input byte 8           addr=10.222.0.1:50864 code=403 dev=proffalken/user op=CreateDevice ref=26cced8f-d4d5-4d82-5ff9-60ef656d104e uri=/api/v1/crud/proffalken/laptop
```

**Comment by proffalken** [comment]
Interestingly, I don't get this error when using the Python library to access the API as documented at http://connectordb-python.readthedocs.io/en/latest/tutorial.html#basics

**Comment by proffalken** [comment]
Sorry, just managed to get the Android app working with this as well, so it's definitely the linux desktop client and the Chrome plugin that are affected by this.

Let me know the information you need to narrow it down.

**Comment by dkumor** [comment]
So the steps to repeat this are:
- Install connectordb_desktop_0.3.0git1114_linux_amd64.tar.gz from the alpha downloads
- Log in, and attempt to add a device through the UI
- also attempt to install the chrome extension

Both of these fail with a base64 error? I will attempt a clean install, and see if I can repeat this, since I am unable to reproduce on my laptop.

Can you tell me what distro you're using?

**Comment by dkumor** [comment]
I have found the error. It turns out that you are using an old version of ConnectorDB (0.3.0a1), with the most recent versions of the clients. Newer versions of ConnectorDB have support for device icons, and the clients exploit this support.

The android client is currently in the process of being updated, but has not yet gained support for icons, which is why it works.

There are two alternatives:
- You can manually create the devices using the UI, and then run the desktop client and the chrome extension pointing them to that device name. That will have the extensions not create their own icons.
- You can install the bleeding-edge alpha release which not only has support for icons, but also lots of plotting functionality! The bleeding-edge releases are available here: https://keybase.pub/dkumor/connectordb/.

**Comment by proffalken** [comment]
Brilliant, thanks @dkumor :)

FWIW, I'm running this on Arch Linux and using those instructions, I just had the wrong binary downloaded.

I'll try the new one shortly.

**Comment by dkumor** [comment]
No problem :) Please let me know if this fixes the issue!

**Comment by proffalken** [comment]
OK, Chrome and Android work with this release, now I just need to create an Arm64 release to run on my pine64... ;)

Can't get the laptop agent to run yet, it seems to want to `include files` but can't find the import:

```
[mmw@gaiman connectordb_desktop_0.3.0git1114_linux_amd64]$ ./connectordb 
Traceback (most recent call last):
  File "laptoplogger.py", line 27, in <module>
    import files
ModuleNotFoundError: No module named 'files'
```

**Comment by proffalken** [comment]
OK, I've built the server on my pine64 following the instructions on the git repo.

It appears to have built successfully, and the server is running and collecting data (I can log in to the Chrome app and the Android app and both are registered and associated with my username).

The problem I now have is that once logged in, the GUI doesn't render - all I get is a white screen.

The build at the login screen is `ConnectorDB 0.3.0git1116`but there is nothing in the logs if I set it to "debug" about failed logins.

Let me know if there is any way I can find more information on this - I promise to write a blog post about getting this up and running on a Pine64 once it's all working :)

**Comment by proffalken** [comment]
More information - "View Source" on the web page after I've logged in shows that the HTML is being generated, however the paths for the JS appear to not be routing properly - `/app/bundle.js` returns a 404.

Any idea how to configure the paths correctly?

**Comment by dkumor** [comment]
For the laptop logger, try cloning the repository https://github.com/connectordb/connectordb-desktop and running it with `./connectordb-desktop`

I will see what the issue is with the laptop release - since you were running it with `./connectordb`, I am assuming that this issue might have been fixed in git (since it's now called connectordb-desktop).

If that fails, go into the src directory and run `python laptoplogger.py`

**Comment by dkumor** [comment]
Now let's debug the render issue for the GUI. The first steps to fix this:
- Is there anything being sent to your browser? That is, is there a page being sent, and it just fails to render? Are there browser errors?

I am guessing that the javascript must not have compiled. Can you check if there is a `bundle.js` in the `bin/app` directory?

**Comment by proffalken** [comment]
```cxdb@pine64:~/connectordb/site/app$ npm run build

> connectordb-frontend@0.0.1 build /home/cxdb/connectordb/site/app
> npm run build:html && npm run build:js && npm run build:branding


> connectordb-frontend@0.0.1 build:html /home/cxdb/connectordb/site/app
> rsync -r ./app ../../bin


> connectordb-frontend@0.0.1 build:js /home/cxdb/connectordb/site/app
> cross-env NODE_ENV=production webpack -p

Hash: 6c1fa7827bcab003939d
Version: webpack 1.14.0
Time: 290ms
    + 1 hidden modules

ERROR in Cannot find module 'babel-core'

> connectordb-frontend@0.0.1 build:branding /home/cxdb/connectordb/site/app
> cp branding/title_logo_light.png ../../bin/app
```

So a bit of researching finds http://stackoverflow.com/questions/35215461/error-in-cannot-find-module-babel-core-using-react-js-webpack-and-express-s which seems to indicate an issue in the babel libraries on install.

Running `npm install babel-core babel-loader --save-dev` and then `npm build dev` from `site/app` appears to finish without any errors, however I still don't have `bundle.js` anywhere.

**Comment by proffalken** [comment]
What is noticeably different is that this time around, the CSS and Javascript libraries are accessible from the View-source, it's just the bundle.js that's missing.

**Comment by dkumor** [comment]
I have restarted the CI builds of frontend. The build will catch any upstream errors if they exist.

We will know in a couple minutes whether it is the build environment you're working in, or if something changed in the dependencies to break the build.

**Comment by dkumor** [comment]
Link to CI: https://travis-ci.org/connectordb/connectordb-frontend
Should be done in a bit (the build takes several minutes)

**Comment by proffalken** [comment]
FWIW, I just copied over the bundle.js files from the release and that works fine, so I guess it just comes down to why these files aren't being generated on my pine

**Comment by dkumor** [comment]
The CI build succeeded without errors - I would try removing `node_modules` folder, then running `npm install`, and finally, `npm run build:js`

That will tell us if you can get a build by following the exact instructions that the CI executed (if so, it means that npm update vs npm install was culprit).

**Comment by proffalken** [comment]
OK, I'll do that shortly.

I've got the laptop connector working from the git repo as well :)

Thanks for all your help on this! :)

**Comment by dkumor** [comment]
I was able to repeat the problem by following the instructions I gave above. The issue is that newer versions of the babel libraries depend on `babel-core` as a peer dependency.

I will fix this issue on Monday, since several dependencies have new versions that need to be tested, and I have a deadline this weekend.

**Comment by proffalken** [comment]
No worries, I'm up and running for now, thanks again for all the help and such a brilliant system! :)

**Comment by dkumor** [comment]
Oh, the system will be getting a lot more powerful in the coming months :)

I hope ConnectorDB is useful to you, and don't hesitate to open issues for things that annoy you or you think would be nice to add!
