### ISSUE TITLE
Questions regarding manually entered data

### ISSUE THREAD

**Issue by robbieh** [connectordb/connectordb#329]
I've fat-fingered data I've manually entered. Is there some way to edit it? 

Also, it seems if I enter JSON number data in the Android app, the number is truncated at the decimal. But if I enter it through the web app, the number remains intact. Do I need to do something different with the schema?

**Comment by dkumor** [comment]
Regarding editing data: no, unfortuantely, there is currently no way to modify data. Originally I thought this was a good design decision (write-only streams allow making certain assumptions in analysis algorithms), I have since found this to be an incessant source of frustration.

The worst part here is that enabling editing would require some pretty serious architecture changes, so it might have to wait for the next major version (and that might take many months).

**Comment by robbieh** [comment]
I'm not sure what else to say about the Android issue. I put in "178.9" and the app pop-up responds "inserted 178". And indeed that is what is inserted.

**Comment by dkumor** [comment]
OK, so I guess it is indeed assuming the data is integers. I will see why it is happening later today.

**Comment by robbieh** [comment]
It's almost certainly right here:
https://github.com/connectordb/connectordb-android/blob/master/src/components/inputs/number.js#L14
The NumberInserter class calls parseInt, just assuming it's an int. I tried to take a swing at fixing it after I found that, but can't get Android Studio to play along nicely today.

**Comment by dkumor** [comment]
Thanks for finding this! It does indeed look like the issue. I'll publish a fix to it today (didn't get to it yesterday, unfortunately).

PS: If you have any questions about getting Android Studio to play with the app code, I'll happily help (and add more detailed instructions to the readme).

**Comment by dkumor** [comment]
Did the updated app fix the issue?

**Comment by dkumor** [comment]
Closing - Reopen if the issue persists.
